[package]
name = "js"
version = "0.1.0"
authors = ["Jerome Gravel-Niquet <jeromegn@gmail.com>"]

[dependencies]
log = "*"
env_logger = "*"
libc = "*"

[dependencies.js-sys]
path = "../js-sys"
version = "0.1.0"