sudo: required
dist: trusty

language: rust

rust:
  - stable

compiler: clang

git:
  submodules: false

cache:
  cargo: true
  yarn: true
  directories:
    - node_modules
    - v8env/node_modules

install:
  - |
    git submodule update --init third_party/flatbuffers
    cd third_party/flatbuffers
    cmake -G "Unix Makefiles"
    make
    cd $TRAVIS_BUILD_DIR
  - |
    ls -lah third_party/flatbuffers
    export PATH=$PATH:$TRAVIS_BUILD_DIR/third_party/flatbuffers
    flatc --ts -o v8env/src --no-fb-import --gen-mutable msg.fbs
  - |
    nvm install 10
    npm i -g yarn
    yarn install
    cd v8env
    yarn install
    node_modules/.bin/rollup -c
    cd $TRAVIS_BUILD_DIR
  - ls -lah v8env/dist
  - |
    cd libfly/third_party
    wget -qO- https://github.com/superfly/libv8/releases/download/7.1.321/v8-linux-x64.tar.gz | tar xvz
    mv v8/out.gn/lib v8/out.gn/x64.release
    cd $TRAVIS_BUILD_DIR
  - ls -lah libfly/third_party/v8/out.gn
  - sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-3.9 100
  - sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.9 100
  - export CC=/usr/bin/clang
  - export CXX=/usr/bin/clang++