[package]
name = "fly"
version = "0.1.0"
authors = ["Jerome Gravel-Niquet <jeromegn@gmail.com>"]

[profile.release]
debug = true

[dependencies]
tokio = "0.1"
tokio-signal = "0.2"
futures = "0.1"
tokio-io-pool = "*"
log = "*"
env_logger = "*"
lazy_static = "*"
toml = "0.4"
libc = "*"
flatbuffers = { path = "./third_party/flatbuffers/rust/flatbuffers" }
serde = "*"
serde_derive = "1.0"
hyper = "0.12"
http = "0.1"
rusqlite = "0.14"
r2d2_redis = "0.8"
sha2 = "0.7"
sha-1 = "0.7"
url = "1.7"
sourcemap = "2.2"
rand = "0.5"

[build-dependencies]
cc = "*"
cbindgen = "*"