[package]
name = "fly"
version = "0.1.0"
authors = ["Jerome Gravel-Niquet <jeromegn@gmail.com>"]

[dependencies]
tokio = "0.1"
futures = "0.1"
tokio-io-pool = "*"
log = "*"
env_logger = "*"
lazy_static = "*"
toml = "0.4"
libc = "*"
flatbuffers = { path = "./third_party/flatbuffers/rust/flatbuffers" }
# msg = { path = "msg" }
serde = "*"
serde_derive = "1.0"
hyper = "0.12"
libfly = { path = "libfly" }

[workspace]
members = [
    "libfly",
]