[package]
name = "distributed-fly"
version = "0.1.0"
authors = ["Jerome Gravel-Niquet <jeromegn@gmail.com>"]
edition = "2018"

[dependencies]
fly = { path="../" }
log = "*"
lazy_static = "1.1"
tokio = "0.1"
futures = "0.1"
hyper = "0.12"
openssl = {version="0.10",features=["vendored"]}
tokio-openssl = "0.3"
r2d2 = "*"
r2d2_redis = "*"
rmp-serde = "0.13.7"
rmpv = {version="0.4", features=["with-serde"]}
serde_derive = "1"
serde = "1"
serde_json = "*"
rusoto_core = "0.35"
rusoto_kms = "0.35"
rusoto_credential = "0.14"
base64 = "0.10"
config = "0.9"
sha2 = "0.8"
bytes = "*"
prometheus = "0.4"
sentry = "0.12"
slog = {version="2.4.1", features = ["max_level_debug", "release_max_level_info"] }
slog-async = "2.3.0"
slog-envlogger = "2.1.0"
slog-json = "2.3.0"
slog-scope = "4.1.1"
slog-stdlog = "3.0.2"